{{- if and (not .Values.namespaceScoped) .Values.ebpfTopoColl.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-topo-coll
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ebpf-topo-coll
    {{- include "ciroos-agents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ebpf-topo-coll
      {{- include "ciroos-agents.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: EBPF_TOPOLOGY_COLLECTOR_REDUCER_ADDR
          value: http://ebpf-topo-reducer:50051
        - name: EBPF_TOPOLOGY_COLLECTOR_LOG_LEVEL
          value: info
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.ebpfTopoColl.ebpfTopoColl.image.repository }}:{{ .Values.ebpfTopoColl.ebpfTopoColl.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.ebpfTopoColl.ebpfTopoColl.imagePullPolicy }}
        name: ebpf-topo-coll
        resources: {{- toYaml .Values.ebpfTopoColl.ebpfTopoColl.resources | nindent 10
          }}
        securityContext:
        {{- if (not .Values.ebpfTopoColl.ebpfTopoColl.containerSecurityContext) }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - SYS_RESOURCE
          {{- if .Values.ebpfTopoColl.ebpfTopoColl.useSysAdminCap }}
              - SYS_ADMIN
          {{- else }}
              - BPF
              - PERFMON
          {{- end }}
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        {{- else }}
          {{- toYaml .Values.ebpfTopoColl.ebpfTopoColl.containerSecurityContext
            | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /sys/fs/cgroup
          name: cgroup
          readOnly: true
      imagePullSecrets:
      - name: regcred
      securityContext: {{- toYaml .Values.ebpfTopoColl.podSecurityContext | nindent
        8 }}
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroup
{{- end }}
---
{{- if and (not .Values.namespaceScoped) .Values.otelCollector.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  labels:
  {{- include "ciroos-agents.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: otel-collector
    {{- include "ciroos-agents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: otel-collector
      {{- include "ciroos-agents.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: GOGC
          value: "50"
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.otelCollector.otelCollector.image.repository }}:{{ .Values.otelCollector.otelCollector.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.otelCollector.otelCollector.imagePullPolicy }}
        securityContext: {{- toYaml .Values.otelCollector.otelCollector.containerSecurityContext
          | nindent 10 }}
        name: otel-collector
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {{- toYaml .Values.otelCollector.otelCollector.resources | nindent 10
          }}
        volumeMounts:
        - mountPath: /etc/otel/config.yaml
          name: otel-collector-config-vol
          subPath: config.yaml
      imagePullSecrets:
      - name: regcred
      securityContext: {{- toYaml .Values.otelCollector.podSecurityContext | nindent
        8 }}
      volumes:
      - configMap:
          defaultMode: 420
          name: otel-collector-config
        name: otel-collector-config-vol
{{- end }}
