namespaceScoped: false
clusterNamespace: ""
clusterName: "cluster-name"
ingressFqdn: ""
ciroosIngressUrl: ""
ciroosDockerconfigjson: ""
ciroosCaCrt: ""
ciroosTlsCrt: ""
ciroosTlsKey: ""
kind: Secret
beacon:
  beacon:
    image:
      repository: registry.ciroos.ai/netra/beacon
      tag: 00d48859a-a19e43704-260419T1826Z
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
beaconSa:
  serviceAccount:
    annotations: {}
ebpfTopoColl:
  ebpfTopoColl:
    useSysAdminCap: false
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-coll
      tag: fb8ab271e-d3468a69c-260418T1709Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
  enabled: true
  podSecurityContext:
ebpfTopoReducer:
  ebpfTopoReducer:
    image:
      repository: registry.ciroos.ai/netra/ebpf-topo-reducer
      tag: cb1a6d6d0-2b36b3d8e-260417T1439Z
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 256Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
eventrouterController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/eventrouter-controller
      tag: 2f356b608-2b36b3d8e-260417T1439Z
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
eventrouterGvks:
  alertUrl: http://vector-service:8993/k8s/alerts
  dependencyEdgeUrl: http://vector-service:8998/k8s/relationships/v2
  eventUrl: http://vector-service:8991/v2/k8s/events
  heartbeatUrl: http://vector-service:8997/k8s/heartbeat
kubernetesClusterDomain: cluster.local
otelCollector:
  otelCollector:
    image:
      repository: registry.ciroos.ai/netra/otelcollector
      tag: b980b4df3-2b36b3d8e-260417T1439Z
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
sourceRepositoryWatcherController:
  controller:
    image:
      repository: registry.ciroos.ai/netra/source-repository-watcher
      tag: 34c1f5cc4-2b36b3d8e-260417T1439Z
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  enabled: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
vector:
  vector:
    env:
      rustBacktrace: full
      vectorLog: info
    image:
      repository: registry.ciroos.ai/netra/vector
      tag: cc08f82c7-2b36b3d8e-260417T1439Z
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 512Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
  replicas: 1
  serviceAccount:
    annotations: {}
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
